#Import python 3.8
FROM python:3.8

#Define the directory of the application
WORKDIR application

# Copy the file to the Docker image
COPY requirements.txt .

# Run the command to install python packages
RUN pip install -r requirements.txt

# Copy the application repository in the Docker image
COPY /app .

# Run the command to get the articles
RUN cd newscrawler && \
    scrapy crawl url_scrapper -o ./data/jeux_urls.json && \
    scrapy crawl jeux_infos_scrapper

# The command to launch the app
CMD ["python", "app.py"]